---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nvme-exporter
  name: nvme-exporter
spec:
  type: NodePort
  selector:
    app: nvme-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9998
    targetPort: 9998
